### ISSUE TITLE
Instance image move uploaded file nelat

### ISSUE THREAD

**Issue by daffavcd** [chicken-porridge/api-project#6]
-

**Comment by daffavcd** [comment]
some method available

- https://stackoverflow.com/questions/40129372/laravel-how-to-send-image-or-file-to-api/56211502
- one option is encode the file in base 64 and send via POST. But you need to change your 'server' code source – For that, you need to decode it using base64 and then you were able to save it in public folder.

**Comment by daffavcd** [comment]
need follow up from front-end team, otherwise I need direct access to their code @refido

**Comment by refido** [comment]
https://github.com/WahyuIndahp/web-pelaporan

here is their code from front-end team
